/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void idle_task_handler(void);
void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);

void init_systick_timer(uint32_t tick_hz);

__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack);

void init_tasks_stack(void);

void enable_processor_faults(void);

__attribute__((naked)) void switch_sp_to_psp(void);

uint32_t get_psp_value(void);

void save_psp_value(uint32_t current_psp_value);

void update_next_task(void);

void task_delay(uint32_t tick_count);

void unblock_tasks(void);

void update_global_tick_count(void);

void schedule(void);


/* Semi hosting related prototype */
void initialise_monitor_handles(void);

uint8_t current_task = 1; // task1 is running

uint32_t global_tick_count = 0;

typedef struct
{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t  current_state;
	void (*task_handler) (void);
}TCB_t;

TCB_t user_tasks[MAX_TASKS];


int main(void)
{
	enable_processor_faults();

    /* enable semi hosting handles */
    initialise_monitor_handles();
    printf("Initialized semi hosting handles\n");

	init_scheduler_stack(SCHED_STACK_START);

	init_tasks_stack();

	led_init_all();

	init_systick_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();

	/* Loop forever */
	for(;;);
}

void idle_task_handler()
{
	while(1);
}

void task1_handler(void)
{
	while(1)
	{
		printf("This is Task1\n");
		led_on(LED_RED);
		task_delay(1000); // in this program, tick is updated for every 1ms
		led_off(LED_RED);
		task_delay(1000);
	}
}

void task2_handler(void)
{
	while(1)
	{
		printf("This is Task2\n");
		led_on(LED_GREEN);
		task_delay(500); // in this program, tick is updated for every 1ms
		led_off(LED_GREEN);
		task_delay(500);
	}
}

void task3_handler(void)
{
	while(1)
	{
		printf("This is Task3\n");
		led_on(LED_BLUE);
		task_delay(250); // in this program, tick is updated for every 1ms
		led_off(LED_BLUE);
		task_delay(250);
	}
}

void task4_handler(void)
{
	while(1)
	{
		printf("This is Task4\n");
		led_on(LED_WHITE);
		task_delay(125); // in this program, tick is updated for every 1ms
		led_off(LED_WHITE);
		task_delay(125);
	}
}

void init_systick_timer(uint32_t tick_hz)
{
	uint32_t *pSCSR = (uint32_t *) 0xE000E010;
	uint32_t *pSRVR = (uint32_t *) 0xE000E014;
	uint32_t count_value = (SYSTICK_TIM_CLK/tick_hz) - 1;

	/* clear the value into SVR */
	*pSRVR &= ~(0x00FFFFFF);

	/* load the value into SVR */
	*pSRVR |= count_value;

	/* Do SysTick Control and Status register settings */
	*pSCSR |= (1 << 1); // Enable SysTick exception request
	*pSCSR |= (1 << 2); // Clock source = Processor clock

	/* Enable SysTick */
	*pSCSR |= (1 << 0); // Enable the counter
}

__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack)
{
	__asm volatile("MSR MSP,%0": : "r" (sched_top_of_stack)  :  ); //__asm volatile("MSR MSP,R0");
	__asm volatile("BX LR");
}

void init_tasks_stack(void)
{

	user_tasks[0].current_state = TASK_READY_STATE;
	user_tasks[1].current_state = TASK_READY_STATE;
	user_tasks[2].current_state = TASK_READY_STATE;
	user_tasks[3].current_state = TASK_READY_STATE;
	user_tasks[4].current_state = TASK_READY_STATE;

	user_tasks[0].psp_value = IDLE_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;

	user_tasks[0].task_handler = idle_task_handler;
	user_tasks[1].task_handler = task1_handler;
	user_tasks[2].task_handler = task2_handler;
	user_tasks[3].task_handler = task3_handler;
	user_tasks[4].task_handler = task4_handler;

	uint32_t *pPSP;

	for(int i = 0; i < MAX_TASKS; i++)
	{
		pPSP = (uint32_t *) user_tasks[i].psp_value;

		pPSP--;
		*pPSP = DUMMY_XPSR;

		pPSP--; // PC
		*pPSP = (uint32_t)user_tasks[i].task_handler; // Function pointer

		pPSP--; // LR
		*pPSP = 0xFFFFFFFD;

		for(int j = 0; j <= 12; j++)
		{
			pPSP--;
			*pPSP = 0;
		}

		user_tasks[i].psp_value = (uint32_t) pPSP; // Store the new stack pointer
	}
}

void enable_processor_faults(void)
{
	/* enable all configurable exceptions like usage fault, mem manage fault and bus fault */
	uint32_t *pSHCSR = (uint32_t *) 0xE000ED24;

	*pSHCSR |= (1 << 16); // mem manage
	*pSHCSR |= (1 << 17); // bus fault
	*pSHCSR |= (1 << 18); // usage fault
}

uint32_t get_psp_value(void)
{
	return user_tasks[current_task].psp_value;
}

void save_psp_value(uint32_t current_psp_value)
{
	user_tasks[current_task].psp_value = current_psp_value;
}

void update_next_task(void)
{
	uint32_t state = TASK_BLOCKED_STATE;

	for(uint8_t i = 0; i < MAX_TASKS; i++)
	{
		current_task++;
		current_task %= MAX_TASKS;
		state = user_tasks[current_task].current_state;

		if( (state == TASK_READY_STATE) && (current_task != 0) )
			break;
	}

	if(state != TASK_READY_STATE)
		current_task = 0;
}

__attribute__((naked)) void switch_sp_to_psp(void)
{
	/* 1. Initialize the PSP with task1 stack start */

	// get the psp of current task
	__asm volatile ("PUSH {LR}"); // save LR to main
	__asm volatile ("BL get_psp_value"); // After the execution of called function, return value is stored in R0
	__asm volatile ("MSR PSP,R0"); // Configure PSP with R0(in this case psp of T1)
	__asm volatile ("POP {LR}");

	/* 2. change SP to PSP using control register */
	__asm volatile ("MOV R0,0x02"); // Set 2nd bit(SPSEL) for changing SP to PSP
	__asm volatile ("MSR CONTROL,R0");
	__asm volatile ("BX LR");
}

void schedule(void)
{
	// pend the pendSV exception
	uint32_t *pICSR = (uint32_t *) 0xE000ED04;
	*pICSR |= (0x1 << 28);
}

void task_delay(uint32_t tick_count)
{
	// disable interrupt
	INTERRUPT_DISABLE();

	if(current_task) // schedule only when it is not idle task
	{
		user_tasks[current_task].block_count = global_tick_count + tick_count;
		user_tasks[current_task].current_state = TASK_BLOCKED_STATE;
		schedule();
	}

	// enable interrupt
	INTERRUPT_ENABLE();
}

__attribute__((naked)) void PendSV_Handler(void)
{
	__asm volatile ("PUSH {LR}"); // save LR to calling function

	/* Save the context of current task
	 * 1. get current/running task's PSP value
	 * 2. Using the PSP value, store SF2(R4 to R11)
	 * 3. Save the current value of PSP
	 */
	__asm volatile("MRS R0,PSP");
	__asm volatile("STMDB R0!,{R4-R11}"); // R0 will have the new PSP value when after each execution
	__asm volatile("BL save_psp_value"); // R0 already has the PSP value which will be passed as argument

	/* Retrieve the context of next task
	 * 1. Decide next task to run
	 * 2. get its PSP value
	 * 3. Using the PSP value, retrieve the SF2(R4 to R11)
	 * 4. Update the PSP and exit
	 */
	__asm volatile("BL update_next_task");
	__asm volatile("BL get_psp_value"); // After the execution of called function, return value(psp) is stored in R0
	__asm volatile("LDMIA R0!,{R4-R11}");
	__asm volatile("MSR PSP,R0");

	__asm volatile ("POP {LR}"); // Retrieve LR to calling function
	__asm volatile ("BX LR");

}

void update_global_tick_count(void)
{
	global_tick_count++;
}

void unblock_tasks(void)
{
	for(uint8_t i = 0; i < MAX_TASKS; i++)
	{
		if(user_tasks[i].current_state != TASK_READY_STATE)
		{
			if(user_tasks[i].block_count == global_tick_count)
			{
				user_tasks[i].current_state = TASK_READY_STATE;
			}
		}
	}
}

void SysTick_Handler(void)
{
	uint32_t *pICSR = (uint32_t *) 0xE000ED04;

	// update global tick count
	update_global_tick_count();
	unblock_tasks();

	// pend the pendSV exception
	*pICSR |= (0x1 << 28);
}

/* Fault Handlers */
void HardFault_Handler(void)
{
	printf("Exception: Hardfault\n");
	while(1);
}

void MemManage_Handler(void)
{
	printf("Exception: MemManage\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("Exception: BusFault\n");
	while(1);
}
